steps:
 - name: maven:3-jdk-11
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ausgaben-firebase', '--build-arg=JAR_FILE=target/ausgaben-firebase-1.0.0-SNAPSHOT.jar', '.']
images: ['eu.gcr.io/$PROJECT_ID/ausgaben-firebase']